config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  get "page/index"
  root "page#index"
  get "/about" => 'page#about'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates :description, presence: true

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all.order(:description)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
     @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit'}
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.delete
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe has been deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def correct_user
      @recipe= current_user.recipes.find_by(id: params[:id])
      redirect_to recipes_path, notice: "Not authorized to edit this recipe" if @recipe.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def description_error
    if @recipe.errors[:description].size > 0
      return "has-error"
    end

    return ""
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Pocketpalette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pocket Palette</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="http://www.bates.edu/dining/menu/">What's In Commons?</a></li>
        <li><a href="/recipes/new">Submit a Recipe</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse Recipes <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="recipes">Listings from A-Z</a></li>
            <li><a href="#">By Category</a></li>
            <li><a href="#">By User</a></li>
            <li class="divider"></li>
            <li><a href="#">Most Popular This Week</a></li>
            <li class="divider"></li>
          </ul>
        </li>
        <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %> 
        <form class="navbar-form navbar-right" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
      </ul>
      <% if user_signed_in? %>
<p class="text-center">Why hello, <%= current_user.email %></p>
<% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<body>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/page/about.html.erb
<div class="page-header">
  <h1 class="text-center">Ever Find Yourself Stuck With The Same?</h1>
  <br><p class="text-center"><font size="5">Pocket Palette helps you explore Bates College Commons all over again!</font></p>
  <br></br>
<p class="text-center"><img src="http://s22.postimg.org/romc4w2td/bannerfans_11384104_5.gif" alt="Responsive image"></p><br>
<p><font size="4">Pocket Palette is an online, user generated Bates College Commons Cookbook! (Try saying that three times fast...) Here on Pocket Palette, your culinary creativity can run free! Whether you're looking to spice up your commons repetiore, learn from the seasoned pros around campus, or show off your fancy food skills, Pocket Palette is for you! (None of those puns were planned, but they sure do add something, don't they?)</font></p><br>

<p class="text-center"><img src="http://s22.postimg.org/a13kgeiip/bannerfans_11384104_1.gif" alt="Responsive image"></p><br>
<p><font size="4"> Our Mission at Pocket Palette is to provide a creative platform for all culinary coniseuers at Bates. We are exclusively available to the Bates community and aim to provide a common space for commons! <br>
<p class="text-center"><img src="http://s30.postimg.org/6znsxgw75/bannerfans_11384104_2.gif" alt="Responsive image"></p><br>
<h2 class="text-center">Meet our Team!</h2> <br>
<h3 class="text-center">Founder/Lead Engineer</h3>
<p class="text-center"><img src="http://img0.uploadhouse.com/fileuploads/19443/19443880b47ccf916dbb4adad50bd26736057ae6.jpg"></p>
<h3 class="text-center">Rebeccah Bassell '16</h3>

<dl class="dl-horizontal">
  <dt>About</dt>
  <dd>Rebeccah is currently a rising junior at Bates College in Lewiston Maine. She is a Rhetoric Major and self proclaimed foodie. As a super fan of cooking as well as technology, Rebeccah invented Pocket Palette to provide an outlet for her fellow Batesies to get crafty in commons!</dd> 
  <dt>Contact Information</dt>
  <dd>rbassell@bates.edu</dd>
</dl>

app/views/page/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Pocket Palette</h1>
 <div class="row">
 	<div class="col-xs-6 col-md-4"><img class="img-circle" src="http://img4-2.myrecipes.timeinc.net/i/recipes/rs/2002/energy-smoothie-rs-640879-l.jpg"></div>
 	<div class="col-xs-6 col-md-4"><img class="img-circle" src="http://hostedmedia.reimanpub.com/TOH/Images/Photos/37/300x300/exps33961_LT966922D39C.jpg"></div>
 	<div class="col-xs-6 col-md-4"><img class="img-circle" src="http://www.delish.com/cm/delish/images/lo/sour-cherry-fruit-slump-ew0111-lg.jpg"></div>
 </div>
   <br></br>
  <p class="text-center">Because there's more that you can do with what you chew</p>
  <p class="text-center"><a class="btn btn-primary btn-lg" role="button" href="/about">Are You Hungry Yet?</a>

</div>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, html: { class: "form-horizontal"} ) do |f| %>
  <% if @recipe.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">&times;</button>

      <h4>Oops! Something Went Wrong!</h4>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="actions col-sm-offset-2">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes A-Z</h1>
<h3>How to Post Recipes</h3>
<ol>
  <li> Go to http://fb.liox.eu/ and enter in your recipe</li>
  <li> It should follow this format upon entering:</li>
    <li><p><img src="http://img8.uploadhouse.com/fileuploads/19443/1944389830b68c5118c8424863b547c627ba559d.png" alt="Responsive image"></p></li>
  <li> Once you've submited the link to the free hosting service, go to the New Recipes page add your recipe title and link in the description!</li>
</ol>



<table class= "table table-striped">
  <thead>
    <tr>
      <th>Recipes</th>
      <th> </th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.description %></td>
        <td><%= recipe.user.try( :email ) %></td>
        <td><%= time_ago_in_words recipe.created_at %></td>
         <% if current_user == recipe.user %>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td><td></td><td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Recipe', new_recipe_path, class: "btn btn - primary btn -lg"%>
<% end %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>